hydra: 
  run:
    dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - constants: analytic
  - net: analytic
  - optimizer: analytic
  - run: analytic
  - variables: analytic
seed: 666
# can be NEW, LATEST, or a given checkpoint filename
STARTING_POINT: NEW
CHECKPOINT_INTERVAL: 50
MAX_TO_KEEP_NUMBER: 10
MODEL_NAME: analytic
#False-> Simulation; True -> draw 
initialize_each_episode: False
error_filename: error_file.txt
enable_check_numerics: False
loss_choice: mse #huber 
