N_sim_batch: 1280 # 2560
N_episode_length: 66  # 32+2
N_epochs_per_episode: 1
N_minibatch_size: 128
N_episodes: 10000
keras_precision: float32
expectation_type: monomial
sorted_within_batch: false
#expectation_type: pseudo_random
#expectation_pseudo_draws: 10
